development:
  adapter: postgresql
  encoding: unicode
  database: evander_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: evander_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: evander_production
  pool: 5
